apiVersion: backstage.io/v1alpha1
kind: component
metadata:
  annotations:
    backstage.io/techdocs-ref: github://design/doc
    some.annotation: value
  namespace: distribution
  name: delivery-tracker
  title: Delivery App
  description: delivery app component responsible for transit processes
  tags: ["framework:react", "db:dynamoDB"]
  links:
    - title: Wiki
      url: https://backstage.core.shopist.org/docs/default/component/delivery-cancel
      icon: help
    - title: runbook
      url: https://backstage.core.shopist.org/docs/default/component/rollback
      icon: help
    - title: source
      url: https://gitlab.shopist.org/shopist/delivery-app
      icon: gitlab
    - title: jira
      url: https://shopist.atlassian.net/browse/DA
      icon: help
    - title: diagram
      url: https://shopist.atlassian.net/wiki/spaces/DA
      icon: help
  ignore-attribute:
    id: 1
    value: "ignore_value"
spec:
  type: service
  lifecycle: test
  owner: TMH Careplan
  system: Appointments
